// Generated by scripts/build.mjs — do not edit; edit src/client/index.tsx.
window.__ModuleLoader__.load({
  id: "dsh-reminder-clock",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name2 in all)
    __defProp(target, name2, { get: all[name2], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.tsx
var index_exports = {};
__export(index_exports, {
  apply: () => apply,
  inject: () => inject,
  name: () => name
});
module.exports = __toCommonJS(index_exports);
var import_react = __toESM(require("react"), 1);

// src/holidays.mjs
var BUNDLED_HOLIDAYS_PROVIDER = "https://timor.tech/api/holiday/year/";
var BUNDLED_HOLIDAYS = {
  2025: {
    "01-01": [1, "元旦"],
    "01-26": [0, "春节前补班"],
    "01-28": [1, "除夕"],
    "01-29": [1, "初一"],
    "01-30": [1, "初二"],
    "01-31": [1, "初三"],
    "02-01": [1, "初四"],
    "02-02": [1, "初五"],
    "02-03": [1, "初六"],
    "02-04": [1, "初七"],
    "02-08": [0, "春节后补班"],
    "04-04": [1, "清明节"],
    "04-05": [1, "清明节"],
    "04-06": [1, "清明节"],
    "04-27": [0, "劳动节前补班"],
    "05-01": [1, "劳动节"],
    "05-02": [1, "劳动节"],
    "05-03": [1, "劳动节"],
    "05-04": [1, "劳动节"],
    "05-05": [1, "劳动节"],
    "05-31": [1, "端午节"],
    "06-01": [1, "端午节"],
    "06-02": [1, "端午节"],
    "09-28": [0, "国庆节前补班"],
    "10-01": [1, "国庆节"],
    "10-02": [1, "国庆节"],
    "10-03": [1, "国庆节"],
    "10-04": [1, "国庆节"],
    "10-05": [1, "国庆节"],
    "10-06": [1, "中秋节"],
    "10-07": [1, "国庆节"],
    "10-08": [1, "国庆节"],
    "10-11": [0, "国庆节后补班"]
  },
  2026: {
    "01-01": [1, "元旦"],
    "01-02": [1, "元旦"],
    "01-03": [1, "元旦"],
    "01-04": [0, "元旦后补班"],
    "02-14": [0, "春节前补班"],
    "02-15": [1, "春节"],
    "02-16": [1, "除夕"],
    "02-17": [1, "初一"],
    "02-18": [1, "初二"],
    "02-19": [1, "初三"],
    "02-20": [1, "初四"],
    "02-21": [1, "初五"],
    "02-22": [1, "初六"],
    "02-23": [1, "初七"],
    "02-28": [0, "春节后补班"],
    "04-04": [1, "清明节"],
    "04-05": [1, "清明节"],
    "04-06": [1, "清明节"],
    "05-01": [1, "劳动节"],
    "05-02": [1, "劳动节"],
    "05-03": [1, "劳动节"],
    "05-04": [1, "劳动节"],
    "05-05": [1, "劳动节"],
    "05-09": [0, "劳动节后补班"],
    "06-19": [1, "端午节"],
    "06-20": [1, "端午节"],
    "06-21": [1, "端午节"],
    "09-20": [0, "中秋节前补班"],
    "09-25": [1, "中秋节"],
    "09-26": [1, "中秋节"],
    "09-27": [1, "中秋节"],
    "10-01": [1, "国庆节"],
    "10-02": [1, "国庆节"],
    "10-03": [1, "国庆节"],
    "10-04": [1, "国庆节"],
    "10-05": [1, "国庆节"],
    "10-06": [1, "国庆节"],
    "10-07": [1, "国庆节"],
    "10-10": [0, "国庆节后补班"]
  }
};

// src/shared/config.mjs
var MAX_ITEMS = 24;
var MAX_CALENDAR_OVERRIDES = 400;
var TIME_RE = /^([01][0-9]|2[0-3]):[0-5][0-9]$/;
var DAY_POLICY_IDS = ["every", "workday", "restday"];
var LEGACY_DAY_POLICIES = { lunch: "workday", offwork: "workday" };
var DEFAULT_BIG_WORKDAYS = [1, 2, 3, 4, 5, 6];
var DEFAULT_SMALL_WORKDAYS = [1, 2, 3, 4, 5];
var POSITION_IDS = ["bottom-right", "top-right"];
var FREE_ANCHORS = ["left", "right"];
var FREE_VANCHORS = ["top", "bottom"];
var FREE_POS_MAX = 2e4;
function safeString(value, fallback, max) {
  if (typeof value !== "string") return fallback;
  const trimmed = value.trim();
  if (trimmed.length === 0) return fallback;
  return trimmed.slice(0, max);
}
function safeEmoji(value, fallback) {
  const raw = typeof value === "string" ? value.trim() : "";
  if (raw.length === 0) return fallback;
  return Array.from(raw).slice(0, 2).join("");
}
function clampInt(value, min, max, fallback) {
  const n = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, Math.round(n)));
}
function normalizeDate(value) {
  if (typeof value !== "string") return void 0;
  const trimmed = value.trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) return void 0;
  const ms = Date.parse(trimmed + "T00:00:00Z");
  if (!Number.isFinite(ms)) return void 0;
  return new Date(ms).toISOString().slice(0, 10) === trimmed ? trimmed : void 0;
}
function normalizeWorkdays(value, fallback) {
  if (!Array.isArray(value)) return fallback.slice();
  const seen = /* @__PURE__ */ new Set();
  for (const entry of value) {
    const day = typeof entry === "number" ? entry : Number(entry);
    if (!Number.isInteger(day) || day < 1 || day > 7) continue;
    seen.add(day);
  }
  if (seen.size === 0) return fallback.slice();
  return Array.from(seen).sort((a, b) => a - b);
}
function normalizeItem(raw, index) {
  const src = typeof raw === "object" && raw !== null ? raw : {};
  const id = safeString(src.id, "item-" + (index + 1), 48).replace(/[^A-Za-z0-9_-]/g, "-");
  const time = typeof src.time === "string" && TIME_RE.test(src.time.trim()) ? src.time.trim() : "12:00";
  return {
    id,
    label: safeString(src.label, "提醒", 24),
    emoji: safeEmoji(src.emoji, "⏰"),
    time,
    enabled: src.enabled !== false,
    days: DAY_POLICY_IDS.includes(src.days) ? src.days : LEGACY_DAY_POLICIES[id] || "every",
    message: typeof src.message === "string" ? src.message.trim().slice(0, 120) : ""
  };
}
function normalizeFreePos(raw) {
  if (typeof raw !== "object" || raw === null) return null;
  const anchor = FREE_ANCHORS.includes(raw.anchor) ? raw.anchor : null;
  const vAnchor = FREE_VANCHORS.includes(raw.vAnchor) ? raw.vAnchor : null;
  if (anchor === null || vAnchor === null) return null;
  return {
    anchor,
    x: clampInt(raw.x, 0, FREE_POS_MAX, 16),
    vAnchor,
    y: clampInt(raw.y, 0, FREE_POS_MAX, 52)
  };
}
function normalizeCalendar(raw) {
  const src = typeof raw === "object" && raw !== null ? raw : {};
  const rawCycle = typeof src.cycle === "object" && src.cycle !== null ? src.cycle : null;
  const anchor = rawCycle === null ? void 0 : normalizeDate(rawCycle.anchor);
  const overrides = {};
  const rawOverrides = typeof src.overrides === "object" && src.overrides !== null ? src.overrides : {};
  for (const [key, value] of Object.entries(rawOverrides).slice(0, MAX_CALENDAR_OVERRIDES)) {
    const date = normalizeDate(key);
    if (date === void 0) continue;
    if (value === 1 || value === true) overrides[date] = 1;
    else if (value === 0 || value === false) overrides[date] = 0;
  }
  return {
    cycle: anchor === void 0 ? null : { anchor, anchorKind: rawCycle.anchorKind === "small" ? "small" : "big" },
    bigWorkdays: normalizeWorkdays(src.bigWorkdays, DEFAULT_BIG_WORKDAYS),
    smallWorkdays: normalizeWorkdays(src.smallWorkdays, DEFAULT_SMALL_WORKDAYS),
    overrides,
    sync: src.sync !== false
  };
}
function defaultConfig() {
  return {
    version: 1,
    enabled: true,
    items: [
      {
        id: "lunch",
        label: "午餐",
        emoji: "🍚",
        time: "12:00",
        enabled: true,
        days: "workday",
        message: "干饭干饭！干饭不积极，思想有问题！"
      },
      {
        id: "offwork",
        label: "下班",
        emoji: "🌇",
        time: "18:00",
        enabled: true,
        days: "workday",
        message: "牛马收工~"
      }
    ],
    options: { showCountdown: true, snoozeMinutes: 5, graceMinutes: 3, position: "bottom-right", freePos: null },
    calendar: {
      cycle: null,
      bigWorkdays: DEFAULT_BIG_WORKDAYS.slice(),
      smallWorkdays: DEFAULT_SMALL_WORKDAYS.slice(),
      overrides: {},
      sync: true
    }
  };
}
function normalizeConfig(raw) {
  const src = typeof raw === "object" && raw !== null ? raw : {};
  const rawItems = Array.isArray(src.items) ? src.items.slice(0, MAX_ITEMS) : null;
  let items = rawItems === null ? defaultConfig().items.map(normalizeItem) : rawItems.map(normalizeItem);
  const seen = /* @__PURE__ */ new Set();
  items = items.filter((item) => {
    if (seen.has(item.id)) return false;
    seen.add(item.id);
    return true;
  });
  const rawOptions = typeof src.options === "object" && src.options !== null ? src.options : {};
  return {
    version: 1,
    enabled: src.enabled !== false,
    items,
    options: {
      showCountdown: rawOptions.showCountdown !== false,
      snoozeMinutes: clampInt(rawOptions.snoozeMinutes, 1, 120, 5),
      graceMinutes: clampInt(rawOptions.graceMinutes, 0, 60, 3),
      position: POSITION_IDS.includes(rawOptions.position) ? rawOptions.position : "bottom-right",
      freePos: normalizeFreePos(rawOptions.freePos)
    },
    calendar: normalizeCalendar(src.calendar)
  };
}

// src/client/index.tsx
var import_jsx_runtime = require("react/jsx-runtime");
var { useEffect, useRef, useState } = import_react.default;
var useStore = import_react.default.useSyncExternalStore || function useStoreShim(subscribeFn, getSnapshot) {
  const [, force] = useState(0);
  useEffect(() => subscribeFn(() => force((n) => n + 1)), [subscribeFn]);
  return getSnapshot();
};
var API = "/api/reminder-clock/config";
var API_HOLIDAYS = "/api/reminder-clock/holidays";
var HOLIDAY_PROVIDER_URL = "https://timor.tech/api/holiday/year/";
var HOLIDAY_MAX_AGE_MS = 30 * 24 * 60 * 60 * 1e3;
var HOLIDAY_RETRY_MS = 24 * 60 * 60 * 1e3;
var HOLIDAY_HOST_TIMEOUT_MS = 8e3;
var HOLIDAY_DIRECT_TIMEOUT_MS = 8e3;
var HOLIDAY_DIRECT_ATTEMPTS = 2;
var CONFIG_KEY = "dsh.reminderClock.v1";
var FIRED_KEY = "dsh.reminderClock.fired.v1";
var MUTED_KEY = "dsh.reminderClock.muted.v1";
var HOLIDAY_KEY = "dsh.reminderClock.holidays.v1";
var POSITION_ANCHORS = {
  "bottom-right": { right: 16, bottom: 10 },
  "top-right": { right: 16, top: 80 }
};
var POSITIONS = [
  { id: "bottom-right", label: "右下角（默认；面板向上弹）" },
  { id: "top-right", label: "右上角（面板向下弹）" }
];
var DAY_POLICIES = [
  { id: "every", label: "每天" },
  { id: "workday", label: "仅工作日" },
  { id: "restday", label: "仅休息日" }
];
var WEEKDAY_LABELS = ["一", "二", "三", "四", "五", "六", "日"];
var mergedHolidays = mergeHolidayMaps(BUNDLED_HOLIDAYS, {});
var CSS = `
.drc-root{position:fixed;z-index:60;display:flex;flex-direction:column;gap:8px;pointer-events:none;font-family:"Segoe UI Variable Text","Segoe UI",-apple-system,"PingFang SC","Microsoft YaHei UI",sans-serif;color:var(--dsw-alias-label-primary,#1b1e26)}
.drc-root.pos-top-right{top:${POSITION_ANCHORS["top-right"].top}px;right:${POSITION_ANCHORS["top-right"].right}px;align-items:flex-end}
.drc-root.pos-bottom-right{bottom:${POSITION_ANCHORS["bottom-right"].bottom}px;right:${POSITION_ANCHORS["bottom-right"].right}px;align-items:flex-end;flex-direction:column-reverse}
.drc-root.drc-free{align-items:flex-start}
.drc-root.drc-free.drc-free-right{align-items:flex-end}
.drc-root.drc-free.drc-free-up{flex-direction:column-reverse}
.drc-root.drc-dragging{cursor:grabbing;user-select:none}
.drc-root.drc-dragging .drc-pill{cursor:grabbing}
.drc-card,.drc-pill,.drc-panel{pointer-events:auto;background:var(--dsw-alias-bg-overlay,#fff);border:1px solid var(--dsw-alias-border-l1,rgba(20,24,35,.10));border-radius:14px;box-shadow:0 10px 30px rgba(15,20,35,.16),0 1px 2px rgba(15,20,35,.10)}
.drc-pill{display:inline-flex;align-items:center;gap:8px;padding:6px 12px;border:none;border-radius:999px;font:inherit;font-size:12.5px;cursor:grab;touch-action:none;transition:transform .12s ease,box-shadow .12s ease}
.drc-pill:hover{transform:translateY(-1px);box-shadow:0 12px 26px rgba(15,20,35,.2)}
.drc-pill-emoji{font-size:14px;line-height:1}
.drc-pill-label{font-weight:600;color:var(--dsw-alias-label-primary,#1b1e26)}
.drc-pill-time{font-variant-numeric:tabular-nums;font-weight:700;color:var(--dsw-alias-brand-primary,#3b82f6)}
.drc-pill-hint{color:var(--dsw-alias-label-secondary,#5b6472);font-weight:500}
.drc-card{width:288px;padding:14px;display:flex;flex-direction:column;gap:10px;border-color:var(--dsw-alias-brand-primary,#3b82f6);animation:drc-in .22s ease both}
@keyframes drc-in{from{opacity:0;transform:translateY(-6px) scale(.98)}to{opacity:1;transform:none}}
.drc-card-head{display:flex;align-items:center;gap:9px}
.drc-card-emoji{font-size:24px;line-height:1}
.drc-card-title{font-size:14px;font-weight:700}
.drc-card-at{font-size:11.5px;color:var(--dsw-alias-label-secondary,#5b6472);font-variant-numeric:tabular-nums}
.drc-card-msg{margin:0;font-size:12.5px;line-height:1.5;color:var(--dsw-alias-label-secondary,#5b6472);word-break:break-word}
.drc-card-actions{display:flex;flex-wrap:wrap;gap:6px;justify-content:flex-end}
.drc-btn{display:inline-flex;align-items:center;gap:5px;white-space:nowrap;padding:5px 10px;border:1px solid var(--dsw-alias-border-l1,rgba(20,24,35,.12));border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary,#5b6472);cursor:pointer;font:inherit;font-size:12px;transition:background .12s ease,color .12s ease}
.drc-btn:hover{background:rgba(127,140,165,.12);color:var(--dsw-alias-label-primary,#1b1e26)}
.drc-btn-primary{background:var(--dsw-alias-brand-primary,#3b82f6);border-color:var(--dsw-alias-brand-primary,#3b82f6);color:#fff;font-weight:600}
.drc-btn-primary:hover{background:var(--dsw-alias-brand-primary,#3b82f6);color:#fff;filter:brightness(1.06)}
.drc-btn:disabled{opacity:.5;cursor:default}
.drc-panel{width:280px;padding:12px;display:flex;flex-direction:column;gap:8px}
.drc-panel-head{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}
.drc-panel-title{font-size:13px;font-weight:700;flex:none}
.drc-row,.drc-holiday{display:grid;grid-template-columns:20px minmax(0,1fr) 40px 58px 62px;gap:6px;align-items:center;padding:5px 6px;border-radius:9px;font-size:12.5px}
.drc-row:hover{background:rgba(127,140,165,.10)}
.drc-row-emoji{text-align:center}
.drc-row-label,.drc-holiday-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.drc-row-time,.drc-holiday-date{font-variant-numeric:tabular-nums;text-align:right;color:var(--dsw-alias-label-secondary,#5b6472)}
.drc-row-in,.drc-holiday-in{font-variant-numeric:tabular-nums;font-weight:700;text-align:right;color:var(--dsw-alias-brand-primary,#3b82f6)}
.drc-row-off{color:var(--dsw-alias-label-secondary,#5b6472);font-size:11.5px}
.drc-row-next{background:rgba(59,130,246,.10)}
.drc-hint{margin:0;font-size:11.5px;line-height:1.5;color:var(--dsw-alias-label-secondary,#5b6472)}
.drc-panel-foot{display:flex;align-items:center;justify-content:space-between;gap:8px;border-top:1px solid var(--dsw-alias-border-l1,rgba(20,24,35,.08));padding-top:8px}
.drc-holiday{background:var(--dsw-alias-bg-base,rgba(20,24,35,.04))}
.drc-holiday-on{background:var(--dsw-alias-bg-overlay,#fff);box-shadow:inset 0 0 0 1px var(--dsw-alias-state-warn-primary,#b45309)}
.drc-holiday-name{font-weight:700}
.drc-holiday-days{justify-self:center;font-size:10.5px;color:var(--dsw-alias-label-secondary,#5b6472);white-space:nowrap}
.drc-holiday-on .drc-holiday-in{color:var(--dsw-alias-state-warn-primary,#b45309)}
.drc-settings{max-width:760px;display:flex;flex-direction:column;gap:18px;font-size:13px;color:var(--dsw-alias-label-primary,#1b1e26)}
.drc-sec-head h2{margin:0 0 4px;font-size:15px;font-weight:700}
.drc-sec-head p{margin:0;font-size:12.5px;line-height:1.6;color:var(--dsw-alias-label-secondary,#5b6472)}
.drc-group{display:flex;flex-direction:column;gap:8px;border:1px solid var(--dsw-alias-border-l1,rgba(20,24,35,.10));border-radius:12px;padding:12px}
.drc-group-title{font-size:12.5px;font-weight:700;display:flex;align-items:center;justify-content:space-between;gap:8px}
.drc-item{display:grid;grid-template-columns:24px 56px minmax(80px,1fr) 104px 92px 64px 68px;gap:8px;align-items:center;padding:2px 0}
.drc-item-head{display:grid;grid-template-columns:24px 56px minmax(80px,1fr) 104px 92px 64px 68px;gap:8px;font-size:11.5px;color:var(--dsw-alias-label-secondary,#5b6472);padding:0 2px}
.drc-item-head span{white-space:nowrap}
.drc-more{grid-column:1;width:24px;height:24px;padding:0;border:none;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary,#5b6472);cursor:pointer;font:inherit;font-size:11px;line-height:1}
.drc-more:hover{background:rgba(127,140,165,.14)}
.drc-more-set{color:var(--dsw-alias-brand-primary,#3b82f6)}
.drc-item-more{grid-column:1 / -1;display:flex;align-items:center;gap:8px;padding:2px 2px 6px}
.drc-item-more .drc-input{flex:1;min-width:0}
.drc-item-more .drc-sub{flex:none}
.drc-input{box-sizing:border-box;width:100%;height:30px;border:1px solid var(--dsw-alias-border-l2,rgba(20,24,35,.2));border-radius:8px;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-primary,#1b1e26);padding:0 8px;font:inherit;font-size:12.5px}
.drc-input:focus{outline:none;border-color:var(--dsw-alias-brand-primary,#3b82f6);box-shadow:0 0 0 2px rgba(59,130,246,.16)}
.drc-input-emoji{text-align:center;padding:0}
.drc-check{display:inline-flex;align-items:center;gap:6px;font-size:12.5px;color:var(--dsw-alias-label-secondary,#5b6472);white-space:nowrap;cursor:pointer}
.drc-options{display:flex;flex-wrap:wrap;gap:10px 18px;align-items:center}
.drc-num{width:72px}
.drc-select{height:30px;border:1px solid var(--dsw-alias-border-l2,rgba(20,24,35,.2));border-radius:8px;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-primary,#1b1e26);padding:0 6px;font:inherit;font-size:12.5px}
.drc-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}
.drc-status{font-size:12px;color:var(--dsw-alias-label-secondary,#5b6472)}
.drc-status-ok{color:var(--dsw-alias-state-success-primary,#16a34a)}
.drc-status-err{color:var(--dsw-alias-state-error-primary,#dc2626)}
.drc-warn{margin:0;font-size:12px;line-height:1.6;color:var(--dsw-alias-state-warn-primary,#b45309)}
.drc-empty{margin:0;font-size:12.5px;color:var(--dsw-alias-label-secondary,#5b6472)}
.drc-day-chip{display:inline-flex;align-items:center;gap:6px;min-width:0;font-size:11.5px;color:var(--dsw-alias-label-secondary,#5b6472)}
.drc-day-dot{width:7px;height:7px;border-radius:50%;background:var(--dsw-alias-state-success-primary,#16a34a);flex:none}
.drc-day-rest .drc-day-dot{background:var(--dsw-alias-state-warn-primary,#b45309)}
.drc-tag{justify-self:center;max-width:100%;overflow:hidden;text-overflow:ellipsis;font-size:10.5px;padding:1px 5px;border-radius:999px;border:1px solid var(--dsw-alias-border-l1,rgba(20,24,35,.12));color:var(--dsw-alias-label-secondary,#5b6472);white-space:nowrap}
.drc-tag-skip{color:var(--dsw-alias-state-warn-primary,#b45309);border-color:currentColor}
.drc-weekdays{display:flex;gap:4px;flex-wrap:wrap}
.drc-weekday{width:26px;height:26px;border:1px solid var(--dsw-alias-border-l2,rgba(20,24,35,.2));border-radius:7px;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-secondary,#5b6472);font:inherit;font-size:12px;cursor:pointer}
.drc-weekday-on{background:var(--dsw-alias-brand-primary,#3b82f6);border-color:var(--dsw-alias-brand-primary,#3b82f6);color:#fff;font-weight:700}
.drc-sub{font-size:11.5px;color:var(--dsw-alias-label-secondary,#5b6472);margin:0}
.drc-inline{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.drc-date{width:138px}
.drc-override-list{display:flex;flex-wrap:wrap;gap:6px}
.drc-override{display:inline-flex;align-items:center;gap:5px;font-size:11.5px;padding:3px 6px;border:1px solid var(--dsw-alias-border-l1,rgba(20,24,35,.12));border-radius:8px}
.drc-override-x{border:none;background:transparent;color:var(--dsw-alias-label-secondary,#5b6472);cursor:pointer;font:inherit;padding:0 2px}
.drc-daytag{font-size:11.5px;color:var(--dsw-alias-label-secondary,#5b6472)}
@media(prefers-reduced-motion:reduce){.drc-card{animation:none}.drc-pill{transition:none}}
`;
function timeToSeconds(time) {
  const match = /^([01][0-9]|2[0-3]):([0-5][0-9])$/.exec(String(time || ""));
  if (match === null) return 0;
  return Number(match[1]) * 3600 + Number(match[2]) * 60;
}
function startOfDay(ms) {
  const d = new Date(ms);
  d.setHours(0, 0, 0, 0);
  return d.getTime();
}
function dayKey(ms) {
  const d = new Date(ms);
  const pad = (n) => n < 10 ? "0" + n : String(n);
  return d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate());
}
function dateAtMidnight(key) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(key || ""));
  if (match === null) return NaN;
  const d = new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
  d.setHours(0, 0, 0, 0);
  return d.getTime();
}
function weekdayNumber(ms) {
  return (new Date(ms).getDay() + 6) % 7 + 1;
}
function mondayOf(ms) {
  const d = new Date(ms);
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() - (d.getDay() + 6) % 7);
  return d.getTime();
}
function mergeHolidayMaps(bundled, runtime) {
  const merged = {};
  for (const [year, days] of Object.entries(bundled !== null && typeof bundled === "object" ? bundled : {})) {
    merged[year] = days;
  }
  for (const [year, days] of Object.entries(runtime !== null && typeof runtime === "object" ? runtime : {})) {
    if (days !== null && typeof days === "object" && Object.keys(days).length > 0) merged[year] = days;
  }
  return merged;
}
function holidayEntry(key) {
  const year = mergedHolidays[key.slice(0, 4)];
  if (year === void 0 || year === null) return void 0;
  const entry = year[key.slice(5)];
  return Array.isArray(entry) ? entry : void 0;
}
function cycleKind(ms, calendar) {
  const cycle = calendar !== null && typeof calendar === "object" ? calendar.cycle : null;
  if (cycle === null || cycle === void 0) return null;
  const anchor = dateAtMidnight(cycle.anchor);
  if (!Number.isFinite(anchor)) return null;
  const weeks = Math.round((mondayOf(ms) - mondayOf(anchor)) / (7 * 864e5));
  const index = (weeks % 2 + 2) % 2;
  const first = cycle.anchorKind === "small" ? "small" : "big";
  if (index === 0) return first;
  return first === "big" ? "small" : "big";
}
function dayInfo(ms, config) {
  const calendar = config !== null && config !== void 0 && config.calendar !== void 0 && config.calendar !== null ? config.calendar : normalizeCalendar(void 0);
  const key = dayKey(ms);
  const week = cycleKind(ms, calendar);
  const override = calendar.overrides[key];
  if (override === 1) return { kind: "restday", reason: "override", name: "手动放假", week };
  if (override === 0) return { kind: "workday", reason: "override", name: "手动补班", week };
  const entry = holidayEntry(key);
  if (entry !== void 0) {
    return entry[0] === 1 ? { kind: "restday", reason: "holiday", name: holidayFamily(entry[1] || "法定节假日"), week } : { kind: "workday", reason: "makeup", name: entry[1] || "调休补班", week };
  }
  const weekday = weekdayNumber(ms);
  if (week !== null) {
    const workdays = week === "big" ? calendar.bigWorkdays : calendar.smallWorkdays;
    return {
      kind: workdays.indexOf(weekday) >= 0 ? "workday" : "restday",
      reason: week === "big" ? "bigweek" : "smallweek",
      name: week === "big" ? "大周" : "小周",
      week
    };
  }
  return weekday <= 5 ? { kind: "workday", reason: "weekday", name: "", week: null } : { kind: "restday", reason: "weekend", name: "", week: null };
}
function itemApplies(item, info) {
  if (item.days === "workday") return info.kind === "workday";
  if (item.days === "restday") return info.kind === "restday";
  return true;
}
function dayOffsetLabel(offset, atMs) {
  if (offset <= 0) return "";
  if (offset === 1) return "明天";
  if (offset === 2) return "后天";
  return "周" + WEEKDAY_LABELS[weekdayNumber(atMs) - 1];
}
function dayInfoLabel(info) {
  const base = info.kind === "workday" ? "工作日" : "休息日";
  if (info.reason === "override" || info.reason === "holiday" || info.reason === "makeup") {
    return base + " · " + info.name;
  }
  if (info.week !== null) return base + " · " + info.name;
  return info.kind === "restday" ? base + " · 周末" : base;
}
function dayChipLabel(ms) {
  const key = dayKey(ms);
  return key.slice(5) + " 周" + WEEKDAY_LABELS[weekdayNumber(ms) - 1];
}
function dayPolicyLabel(days) {
  const found = DAY_POLICIES.find((policy) => policy.id === days);
  return found === void 0 ? "每天" : found.label;
}
function daysBetween(fromMs, toMs) {
  return Math.round((startOfDay(toMs) - startOfDay(fromMs)) / 864e5);
}
function holidayFamily(name2) {
  return /^(除夕|初[一二三四五六七八九十]|春节)$/.test(name2) ? "春节" : name2;
}
function holidayRuns(config) {
  const byDay = /* @__PURE__ */ new Map();
  for (const year of Object.keys(mergedHolidays)) {
    const days = mergedHolidays[year];
    if (days === null || typeof days !== "object") continue;
    for (const [monthDay, entry] of Object.entries(days)) {
      if (!Array.isArray(entry) || entry[0] !== 1) continue;
      const ms = dateAtMidnight(year + "-" + monthDay);
      if (!Number.isFinite(ms)) continue;
      const name2 = typeof entry[1] === "string" && entry[1].length > 0 ? entry[1] : "法定节假日";
      byDay.set(ms, holidayFamily(name2));
    }
  }
  for (const [key, value] of Object.entries(config.calendar.overrides)) {
    if (value !== 1) continue;
    const ms = dateAtMidnight(key);
    if (Number.isFinite(ms)) byDay.set(ms, "手动放假");
  }
  const ordered = Array.from(byDay.entries()).sort((a, b) => a[0] - b[0]);
  const runs = [];
  for (const [ms, name2] of ordered) {
    const last = runs[runs.length - 1];
    if (last !== void 0 && addDays(last.endMs, 1) === ms) {
      last.endMs = ms;
      if (last.name !== name2 && last.also.indexOf(name2) < 0) last.also.push(name2);
      continue;
    }
    runs.push({ name: name2, startMs: ms, endMs: ms, also: [] });
  }
  return runs;
}
function nearestHoliday(nowMs, config) {
  const today = startOfDay(nowMs);
  const run = holidayRuns(config).find((candidate) => candidate.endMs >= today);
  if (run === void 0) return null;
  const days = daysBetween(run.startMs, run.endMs) + 1;
  const label = (ms) => dayKey(ms).slice(5) + " 周" + WEEKDAY_LABELS[weekdayNumber(ms) - 1];
  const title = label(run.startMs) + " – " + label(run.endMs) + "，共 " + days + " 天" + (run.also.length > 0 ? "（含 " + run.also.join("、") + "）" : "");
  if (run.startMs <= today) {
    const index = daysBetween(run.startMs, today) + 1;
    const left = days - index;
    return {
      name: run.name,
      days,
      startMs: run.startMs,
      ongoing: true,
      text: left <= 0 ? "最后一天" : "还剩 " + left + " 天",
      title
    };
  }
  const away = daysBetween(today, run.startMs);
  return {
    name: run.name,
    days,
    startMs: run.startMs,
    ongoing: false,
    text: away <= 1 ? "明天开始" : "还有 " + away + " 天",
    title
  };
}
function formatSpan(ms) {
  const total = Math.max(0, Math.floor(ms / 1e3));
  const pad = (n) => n < 10 ? "0" + n : String(n);
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor(total % 3600 / 60);
  const seconds = total % 60;
  return hours > 0 ? hours + ":" + pad(minutes) + ":" + pad(seconds) : pad(minutes) + ":" + pad(seconds);
}
function formatClock(seconds) {
  const pad = (n) => n < 10 ? "0" + n : String(n);
  return pad(Math.floor(seconds / 3600)) + ":" + pad(Math.floor(seconds % 3600 / 60));
}
function messageOf(err) {
  if (err && typeof err.message === "string" && err.message.length > 0) return err.message;
  return String(err);
}
function readLocal(key) {
  try {
    const raw = window.localStorage.getItem(key);
    return raw === null ? void 0 : JSON.parse(raw);
  } catch {
    return void 0;
  }
}
function writeLocal(key, value) {
  try {
    window.localStorage.setItem(key, JSON.stringify(value));
  } catch {
  }
}
function cloneConfig(config) {
  const calendar = normalizeCalendar(config.calendar);
  return {
    version: 1,
    enabled: config.enabled !== false,
    items: config.items.map((item) => ({
      id: item.id,
      label: item.label,
      emoji: item.emoji,
      time: item.time,
      enabled: item.enabled !== false,
      days: item.days,
      message: item.message
    })),
    options: {
      showCountdown: config.options.showCountdown !== false,
      snoozeMinutes: config.options.snoozeMinutes,
      graceMinutes: config.options.graceMinutes,
      position: config.options.position,
      freePos: config.options.freePos === null || config.options.freePos === void 0 ? null : Object.assign({}, config.options.freePos)
    },
    calendar: {
      cycle: calendar.cycle === null ? null : { anchor: calendar.cycle.anchor, anchorKind: calendar.cycle.anchorKind },
      bigWorkdays: calendar.bigWorkdays.slice(),
      smallWorkdays: calendar.smallWorkdays.slice(),
      overrides: Object.assign({}, calendar.overrides),
      sync: calendar.sync !== false
    }
  };
}
var listeners = /* @__PURE__ */ new Set();
var state = {
  status: "loading",
  config: defaultConfig(),
  configRev: 0,
  error: null,
  nowMs: Date.now(),
  alert: null,
  snoozes: [],
  saveState: "idle",
  saveError: null,
  holidays: {
    years: {},
    fetchedAt: null,
    attemptedAt: null,
    provider: BUNDLED_HOLIDAYS_PROVIDER,
    source: "bundled",
    channel: null,
    syncEnabled: true,
    note: null
  },
  holidaySync: "idle",
  holidaySyncVia: null,
  holidaySyncError: null
};
function getState() {
  return state;
}
function subscribe(fn) {
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
}
function setState(patch) {
  state = Object.assign({}, state, patch);
  for (const listener of Array.from(listeners)) {
    try {
      listener();
    } catch (err) {
      console.error("reminder-clock: listener failed", err);
    }
  }
}
function setConfig(raw) {
  setState({ config: normalizeConfig(raw), configRev: state.configRev + 1 });
}
function settingsSnapshot() {
  return state.configRev + "|" + state.status + "|" + state.saveState + "|" + String(state.saveError) + "|" + state.holidaySync + "|" + String(state.holidaySyncVia) + "|" + String(state.holidaySyncError) + "|" + String(state.error);
}
var FIRED_CACHE_MS = 1e3;
var firedCache = null;
function firedMap() {
  const nowMs = Date.now();
  if (firedCache !== null && nowMs < firedCache.expiresAt) return firedCache.map;
  const raw = readLocal(FIRED_KEY);
  const map = typeof raw === "object" && raw !== null ? raw : {};
  firedCache = { map, expiresAt: nowMs + FIRED_CACHE_MS };
  return map;
}
function firedIds(day) {
  const list = firedMap()[day];
  return new Set(Array.isArray(list) ? list : []);
}
function markFired(day, id) {
  const map = firedMap();
  const set = new Set(Array.isArray(map[day]) ? map[day] : []);
  set.add(id);
  map[day] = Array.from(set);
  const kept = Object.keys(map).sort().slice(-3);
  const next = {};
  for (const key of kept) next[key] = map[key];
  writeLocal(FIRED_KEY, next);
  firedCache = { map: next, expiresAt: Date.now() + FIRED_CACHE_MS };
}
function mutedDay() {
  const value = readLocal(MUTED_KEY);
  return typeof value === "string" ? value : null;
}
function muteToday() {
  writeLocal(MUTED_KEY, dayKey(Date.now()));
  setState({ alert: null, snoozes: [] });
}
function unmuteToday() {
  try {
    window.localStorage.removeItem(MUTED_KEY);
  } catch {
  }
  setState({ configRev: state.configRev + 1 });
}
function setHolidays(years, meta) {
  const runtime = Object.assign({}, state.holidays.years, years);
  const next = Object.assign({}, state.holidays, meta, { years: runtime });
  mergedHolidays = mergeHolidayMaps(BUNDLED_HOLIDAYS, runtime);
  writeLocal(HOLIDAY_KEY, {
    years: runtime,
    fetchedAt: next.fetchedAt,
    attemptedAt: next.attemptedAt
  });
  setState({ holidays: next, configRev: state.configRev + 1 });
}
function loadLocalHolidays() {
  const raw = readLocal(HOLIDAY_KEY);
  if (raw === null || raw === void 0 || typeof raw !== "object") return;
  const years = typeof raw.years === "object" && raw.years !== null ? raw.years : {};
  if (Object.keys(years).length === 0) return;
  mergedHolidays = mergeHolidayMaps(BUNDLED_HOLIDAYS, years);
  setState({
    holidays: Object.assign({}, state.holidays, {
      years,
      source: "local",
      channel: "browser",
      fetchedAt: typeof raw.fetchedAt === "string" ? raw.fetchedAt : null,
      attemptedAt: typeof raw.attemptedAt === "string" ? raw.attemptedAt : null
    })
  });
}
function holidaysWantedYears(nowMs) {
  const year = new Date(nowMs).getFullYear();
  return [year, year + 1];
}
function holidayYearsIncomplete(years) {
  return years.some((year) => {
    const days = mergedHolidays[year];
    return days === void 0 || days === null || Object.keys(days).length === 0;
  });
}
function shouldAttemptSync(nowMs) {
  if (!state.config.calendar.sync) return false;
  const years = holidaysWantedYears(nowMs);
  const fetchedMs = state.holidays.fetchedAt === null ? NaN : Date.parse(state.holidays.fetchedAt);
  const fresh = Number.isFinite(fetchedMs) && nowMs - fetchedMs <= HOLIDAY_MAX_AGE_MS;
  if (fresh && !holidayYearsIncomplete(years)) return false;
  const attemptedMs = state.holidays.attemptedAt === null ? NaN : Date.parse(state.holidays.attemptedAt);
  if (Number.isFinite(attemptedMs) && nowMs - attemptedMs <= HOLIDAY_RETRY_MS) return false;
  return true;
}
function parseProviderPayload(payload) {
  const source = payload !== null && typeof payload === "object" ? payload.holiday : null;
  if (source === null || typeof source !== "object") return {};
  const days = {};
  for (const entry of Object.values(source)) {
    if (entry === null || typeof entry !== "object") continue;
    const date = typeof entry.date === "string" ? entry.date : "";
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) continue;
    const name2 = typeof entry.name === "string" && entry.name.trim().length > 0 ? entry.name.trim() : "节假日";
    days[date.slice(5)] = [entry.holiday === true ? 1 : 0, name2.slice(0, 24)];
  }
  return days;
}
async function fetchWithTimeout(url, init, timeoutMs) {
  const controller = typeof AbortController === "function" ? new AbortController() : null;
  const timer = controller === null ? null : window.setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, controller === null ? init : Object.assign({}, init, { signal: controller.signal }));
  } finally {
    if (timer !== null) window.clearTimeout(timer);
  }
}
function isHolidayVerdict(message) {
  return message.includes("empty-payload") || message.includes("HTTP 4");
}
async function fetchHolidaysFromHost(method, years) {
  const res = await fetchWithTimeout(
    API_HOLIDAYS + "?year=" + years.join(","),
    {
      method,
      headers: { accept: "application/json" }
    },
    HOLIDAY_HOST_TIMEOUT_MS
  );
  const data = await res.json().catch(() => null);
  if (data === null || typeof data !== "object" || typeof data.years !== "object" || data.years === null) {
    throw new Error("HTTP " + res.status);
  }
  if (method === "POST" && res.ok !== true) {
    throw new Error(typeof data.syncError === "string" ? data.syncError : "HTTP " + res.status);
  }
  const incoming = {};
  let source = "bundled";
  for (const [year, entry] of Object.entries(data.years)) {
    if (entry === null || typeof entry !== "object") continue;
    if (entry.days !== null && typeof entry.days === "object" && Object.keys(entry.days).length > 0)
      incoming[year] = entry.days;
    if (entry.source === "network" || entry.source === "cache") source = entry.source;
  }
  return {
    years: incoming,
    meta: {
      fetchedAt: typeof data.fetchedAt === "string" ? data.fetchedAt : null,
      provider: typeof data.provider === "string" ? data.provider : BUNDLED_HOLIDAYS_PROVIDER,
      source,
      channel: "host",
      syncEnabled: data.syncEnabled !== false
    }
  };
}
async function fetchHolidaysDirect(years) {
  const settled = await Promise.allSettled(
    years.map(async (year) => {
      let lastError = null;
      for (let attempt = 0; attempt < HOLIDAY_DIRECT_ATTEMPTS; attempt += 1) {
        try {
          const res = await fetchWithTimeout(
            HOLIDAY_PROVIDER_URL + year,
            { headers: { accept: "application/json" } },
            HOLIDAY_DIRECT_TIMEOUT_MS
          );
          if (!res.ok) throw new Error("HTTP " + res.status);
          const days = parseProviderPayload(await res.json());
          if (Object.keys(days).length === 0) throw new Error("empty-payload");
          return { year, days };
        } catch (err) {
          lastError = err;
          if (isHolidayVerdict(messageOf(err))) break;
        }
      }
      throw lastError === null ? new Error("unreachable") : lastError;
    })
  );
  const incoming = {};
  const failures = [];
  for (const item of settled) {
    if (item.status === "fulfilled") incoming[item.value.year] = item.value.days;
    else failures.push(messageOf(item.reason));
  }
  if (Object.keys(incoming).length === 0) {
    throw new Error(failures[0] === void 0 ? "unreachable" : failures[0]);
  }
  return {
    years: incoming,
    meta: {
      fetchedAt: (/* @__PURE__ */ new Date()).toISOString(),
      provider: BUNDLED_HOLIDAYS_PROVIDER,
      source: "network",
      channel: "browser",
      syncEnabled: state.config.calendar.sync
    }
  };
}
async function loadHolidays() {
  loadLocalHolidays();
  const nowMs = Date.now();
  const years = holidaysWantedYears(nowMs);
  let note = null;
  try {
    const host = await fetchHolidaysFromHost("GET", years);
    setHolidays(host.years, Object.assign({ attemptedAt: state.holidays.attemptedAt }, host.meta));
    return;
  } catch (err) {
    note = messageOf(err);
  }
  if (shouldAttemptSync(nowMs)) {
    setState({ holidays: Object.assign({}, state.holidays, { attemptedAt: (/* @__PURE__ */ new Date()).toISOString() }) });
    try {
      const direct = await fetchHolidaysDirect(years);
      setHolidays(direct.years, Object.assign({ attemptedAt: (/* @__PURE__ */ new Date()).toISOString() }, direct.meta));
      return;
    } catch (err) {
      note = messageOf(err);
    }
  }
  setHolidays({}, { source: "bundled", channel: null, note });
}
async function syncHolidays() {
  setState({ holidaySync: "syncing", holidaySyncVia: null, holidaySyncError: null });
  const years = holidaysWantedYears(Date.now());
  const failures = [];
  try {
    const host = await fetchHolidaysFromHost("POST", years);
    setHolidays(host.years, Object.assign({ attemptedAt: (/* @__PURE__ */ new Date()).toISOString(), note: null }, host.meta));
    setState({ holidaySync: "done", holidaySyncVia: "host" });
  } catch (err) {
    failures.push("Host: " + messageOf(err));
    try {
      const direct = await fetchHolidaysDirect(years);
      setHolidays(direct.years, Object.assign({ attemptedAt: (/* @__PURE__ */ new Date()).toISOString(), note: null }, direct.meta));
      setState({ holidaySync: "done", holidaySyncVia: "browser" });
    } catch (err2) {
      failures.push("浏览器: " + messageOf(err2));
      setState({
        holidaySync: "error",
        holidaySyncError: failures.join("；"),
        holidays: Object.assign({}, state.holidays, { note: failures.join("；") })
      });
    }
  }
  window.setTimeout(() => {
    if (state.holidaySync === "done") setState({ holidaySync: "idle" });
  }, 2600);
}
function secondsSince(time, nowMs) {
  const now = new Date(nowMs);
  const elapsed = now.getHours() * 3600 + now.getMinutes() * 60 + now.getSeconds();
  return elapsed - timeToSeconds(time);
}
var NEXT_DAY_SCAN = 21;
function addDays(base, offset) {
  const d = new Date(base);
  d.setDate(d.getDate() + offset);
  return d.getTime();
}
function nextReminder(config, nowMs, snoozes) {
  const pending = snoozes.filter((entry) => entry.atMs > nowMs).sort((a, b) => a.atMs - b.atMs)[0];
  const base = startOfDay(nowMs);
  let best = null;
  for (let offset = 0; offset < NEXT_DAY_SCAN && best === null; offset += 1) {
    const dayStart = addDays(base, offset);
    const info = dayInfo(dayStart, config);
    const fired = firedIds(dayKey(dayStart));
    for (const item of config.items) {
      if (!item.enabled) continue;
      if (offset === 0 && fired.has(item.id)) continue;
      if (!itemApplies(item, info)) continue;
      const atMs = dayStart + timeToSeconds(item.time) * 1e3;
      if (atMs <= nowMs) continue;
      if (best === null || atMs < best.atMs) {
        best = { item, atMs, tomorrow: offset > 0, dayOffset: offset, info, snooze: false };
      }
    }
  }
  if (pending !== void 0 && (best === null || pending.atMs < best.atMs)) {
    return { item: pending.item, atMs: pending.atMs, tomorrow: false, dayOffset: 0, snooze: true };
  }
  return best;
}
function fire(item) {
  setState({ alert: { item, atMs: Date.now() }, nowMs: Date.now() });
}
function tick() {
  const nowMs = Date.now();
  const config = state.config;
  const quiet = !config.enabled || mutedDay() === dayKey(nowMs);
  if (state.alert === null && !quiet) {
    const due = state.snoozes.filter((entry) => entry.atMs <= nowMs).sort((a, b) => a.atMs - b.atMs)[0];
    if (due !== void 0) {
      setState({ snoozes: state.snoozes.filter((entry) => entry !== due) });
      fire(due.item);
      return;
    }
    const day = dayKey(nowMs);
    const fired = firedIds(day);
    const grace = config.options.graceMinutes * 60;
    const info = dayInfo(nowMs, config);
    for (const item of config.items) {
      if (!item.enabled || fired.has(item.id)) continue;
      if (!itemApplies(item, info)) continue;
      const since = secondsSince(item.time, nowMs);
      if (since >= 0 && since <= grace) {
        markFired(day, item.id);
        fire(item);
        return;
      }
    }
  }
  setState({ nowMs });
}
var tickHandle = null;
function startEngine() {
  if (tickHandle !== null) return;
  tickHandle = window.setInterval(() => {
    try {
      tick();
    } catch (err) {
      console.error("reminder-clock: tick failed", err);
    }
  }, 1e3);
  tick();
}
function stopEngine() {
  if (tickHandle === null) return;
  window.clearInterval(tickHandle);
  tickHandle = null;
}
var loaded = false;
var SAVE_TIMEOUT_MS = 12e3;
var CLIENT_OPTION_FALLBACKS = {
  freePos: (value) => value === null || typeof value === "object"
};
var CLIENT_CONFIG_FALLBACKS = ["calendar"];
function carryClientFields(target, rawHostConfig, mirror) {
  const raw = rawHostConfig !== null && typeof rawHostConfig === "object" ? rawHostConfig : {};
  const rawOptions = raw.options !== null && typeof raw.options === "object" ? raw.options : {};
  const mirrorOptions = mirror !== null && mirror !== void 0 && typeof mirror.options === "object" && mirror.options !== null ? mirror.options : {};
  for (const [key, valid] of Object.entries(CLIENT_OPTION_FALLBACKS)) {
    if (Object.prototype.hasOwnProperty.call(rawOptions, key)) continue;
    if (valid(mirrorOptions[key])) target.options[key] = mirrorOptions[key];
  }
  for (const key of CLIENT_CONFIG_FALLBACKS) {
    if (Object.prototype.hasOwnProperty.call(raw, key)) continue;
    if (mirror !== null && mirror !== void 0 && mirror[key] !== void 0) target[key] = mirror[key];
  }
  const rawItems = Array.isArray(raw.items) ? raw.items : [];
  const mirrorItems = mirror !== null && mirror !== void 0 && Array.isArray(mirror.items) ? mirror.items : [];
  if (rawItems.length === 0 || mirrorItems.length === 0) return;
  const mirrorById = /* @__PURE__ */ new Map();
  for (const entry of mirrorItems) {
    if (entry !== null && typeof entry === "object" && typeof entry.id === "string") mirrorById.set(entry.id, entry);
  }
  for (const item of target.items) {
    const rawItem = rawItems.find(
      (candidate) => candidate !== null && typeof candidate === "object" && candidate.id === item.id
    );
    if (rawItem !== void 0 && Object.prototype.hasOwnProperty.call(rawItem, "days")) continue;
    const mirrorItem = mirrorById.get(item.id);
    if (mirrorItem !== void 0 && typeof mirrorItem.days === "string") item.days = mirrorItem.days;
  }
}
function loadLocalConfig() {
  const raw = readLocal(CONFIG_KEY);
  if (raw !== void 0 && raw !== null && typeof raw === "object") setConfig(raw);
}
async function loadConfig() {
  if (loaded) return;
  loaded = true;
  loadLocalConfig();
  const mirror = readLocal(CONFIG_KEY);
  try {
    const res = await fetch(API, { headers: { accept: "application/json" } });
    if (!res.ok) throw new Error("HTTP " + res.status);
    const data = await res.json();
    if (data !== null && typeof data === "object" && data.ok === true && data.config !== void 0) {
      const hostConfig = normalizeConfig(data.config);
      carryClientFields(hostConfig, data.config, mirror);
      setConfig(hostConfig);
      writeLocal(CONFIG_KEY, hostConfig);
      setState({ status: "ready", error: null });
      return;
    }
    setState({ status: "ready" });
  } catch (err) {
    setState({ status: "ready", error: messageOf(err) });
  }
}
async function saveConfig(draft) {
  const config = normalizeConfig(draft);
  setConfig(config);
  writeLocal(CONFIG_KEY, config);
  setState({ saveState: "saving", saveError: null });
  const guard = window.setTimeout(() => {
    if (state.saveState === "saving") {
      setState({ saveState: "error", saveError: "保存超时（Host 未响应）" });
    }
  }, SAVE_TIMEOUT_MS);
  try {
    const res = await fetch(API, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ config })
    });
    if (!res.ok) throw new Error("HTTP " + res.status);
    const data = await res.json();
    if (data !== null && typeof data === "object" && data.ok === true && data.config !== void 0) {
      const echoed = normalizeConfig(data.config);
      carryClientFields(echoed, data.config, config);
      setConfig(echoed);
      writeLocal(CONFIG_KEY, echoed);
    }
    setState({ saveState: "saved", saveError: null });
    window.setTimeout(() => {
      if (state.saveState === "saved") setState({ saveState: "idle" });
    }, 2400);
  } catch (err) {
    setState({ saveState: "error", saveError: messageOf(err) });
  } finally {
    window.clearTimeout(guard);
  }
}
var Boundary = class extends import_react.default.Component {
  constructor(props) {
    super(props);
    this.state = { failed: false };
  }
  static getDerivedStateFromError() {
    return { failed: true };
  }
  componentDidCatch(error) {
    console.error("reminder-clock: render failed", error);
  }
  render() {
    return this.state.failed ? null : this.props.children;
  }
};
function AlertCard(props) {
  const { alert, snoozeMinutes, onDismiss, onSnooze, onMute } = props;
  const item = alert.item;
  const clock = formatClock(timeToSeconds(item.time));
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-card", role: "alert", "aria-live": "assertive", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-card-head", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-card-emoji", "aria-hidden": "true", children: item.emoji }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "drc-card-title", children: item.label }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "drc-card-at", children: clock + " 到点了" })
      ] })
    ] }),
    item.message.length > 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-card-msg", children: item.message }) : null,
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-card-actions", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("button", { type: "button", className: "drc-btn", onClick: onMute, children: "今天不再提醒" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("button", { type: "button", className: "drc-btn", onClick: onSnooze, children: snoozeMinutes + " 分钟后再说" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("button", { type: "button", className: "drc-btn drc-btn-primary", onClick: onDismiss, children: "知道了" })
    ] })
  ] });
}
function CountdownPill(props) {
  const { config, nowMs, open, onToggle, onHoverStart, onHoverEnd, onDragStart, onDragMove, onDragEnd, onDragCancel } = props;
  const dragProps = {
    onPointerDown: onDragStart,
    onPointerMove: onDragMove,
    onPointerUp: onDragEnd,
    onPointerCancel: onDragCancel
  };
  const next = nextReminder(config, nowMs, state.snoozes);
  if (next === null) {
    const anyEnabled = config.items.some((item) => item.enabled);
    return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "button",
      {
        type: "button",
        className: "drc-pill",
        onClick: onToggle,
        onMouseEnter: onHoverStart,
        onMouseLeave: onHoverEnd,
        "aria-expanded": open,
        "aria-label": anyEnabled ? "近期没有会提醒的项，悬停或点开查看，可拖动换位置" : "没有启用的提醒项，悬停或点开查看，可拖动换位置",
        ...dragProps,
        children: /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-pill-hint", children: anyEnabled ? "近期无提醒" : "未设置提醒" })
      }
    );
  }
  const span = next.atMs - nowMs;
  const prefix = next.snooze ? "稍后" : dayOffsetLabel(next.dayOffset || 0, next.atMs);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
    "button",
    {
      type: "button",
      className: "drc-pill",
      onClick: onToggle,
      onMouseEnter: onHoverStart,
      onMouseLeave: onHoverEnd,
      "aria-expanded": open,
      "aria-label": prefix.length > 0 ? "下一条：" + prefix + " " + next.item.time + "「" + next.item.label + "」，可拖动换位置" : "距离「" + next.item.label + "」还有 " + formatSpan(span) + "，悬停或点开查看今日安排，可拖动换位置",
      ...dragProps,
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-pill-emoji", "aria-hidden": "true", children: next.item.emoji }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-pill-label", children: next.item.label }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-pill-time", children: formatSpan(span) }),
        prefix.length > 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-pill-hint", children: prefix }) : null
      ]
    }
  );
}
function SchedulePanel(props) {
  const { config, nowMs, muted, onMute, onUnmute, onHoverStart, onHoverEnd } = props;
  const dayStart = startOfDay(nowMs);
  const fired = firedIds(dayKey(nowMs));
  const info = dayInfo(nowMs, config);
  const holiday = nearestHoliday(nowMs, config);
  const next = nextReminder(config, nowMs, state.snoozes);
  const ordered = config.items.slice().sort((a, b) => timeToSeconds(a.time) - timeToSeconds(b.time));
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
    "div",
    {
      className: "drc-panel",
      role: "region",
      "aria-label": "今日提醒",
      onMouseEnter: onHoverStart,
      onMouseLeave: onHoverEnd,
      children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-panel-head", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-panel-title", children: "今日提醒" }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "drc-day-chip" + (info.kind === "restday" ? " drc-day-rest" : ""), children: [
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-day-dot", "aria-hidden": "true" }),
            dayChipLabel(nowMs) + " · " + dayInfoLabel(info)
          ] })
        ] }),
        ordered.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-empty", children: "还没有提醒项，去 设置 → 作息提醒 添加。" }) : ordered.map((item) => {
          const atMs = dayStart + timeToSeconds(item.time) * 1e3;
          const applies = itemApplies(item, info);
          const isNext = next !== null && next.item.id === item.id && (next.dayOffset || 0) === 0;
          const delta = atMs - nowMs;
          const firedAlready = fired.has(item.id);
          const state_ = !item.enabled || !applies ? "off" : firedAlready ? "past" : delta < 0 ? "missed" : "ahead";
          return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-row" + (isNext ? " drc-row-next" : ""), children: [
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-row-emoji", "aria-hidden": "true", children: item.emoji }),
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-row-label", children: item.label }),
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-row-time", children: item.time }),
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-tag" + (applies ? "" : " drc-tag-skip"), children: dayPolicyLabel(item.days) }),
            state_ === "off" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-row-in drc-row-off", children: applies ? "已关闭" : "今日不提醒" }) : state_ === "past" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-row-in drc-row-off", children: "已提醒" }) : state_ === "missed" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-row-in drc-row-off", "aria-label": "已错过，今天不会再补提醒", children: "已错过" }) : /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-row-in", children: formatSpan(delta) })
          ] }, item.id);
        }),
        holiday !== null ? /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
          "div",
          {
            className: "drc-holiday" + (holiday.ongoing ? " drc-holiday-on" : ""),
            "aria-label": holiday.name + "：" + holiday.title,
            children: [
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-row-emoji", "aria-hidden": "true", children: "🎉" }),
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-holiday-name", children: holiday.name }),
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-holiday-date", children: dayKey(holiday.startMs).slice(5) }),
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-holiday-days", children: holiday.days + " 天假" }),
              /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-holiday-in", children: holiday.text })
            ]
          }
        ) : null,
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-hint", children: "设置 → 作息提醒 可改时间与节假日" }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-panel-foot", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-hint", children: muted ? "今天已静音" : "今天正常提醒" }),
          muted ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("button", { type: "button", className: "drc-btn", onClick: onUnmute, children: "恢复提醒" }) : /* @__PURE__ */ (0, import_jsx_runtime.jsx)("button", { type: "button", className: "drc-btn", onClick: onMute, children: "今天不再提醒" })
        ] })
      ]
    }
  );
}
var HOVER_OPEN_MS = 130;
var HOVER_CLOSE_MS = 240;
var DRAG_THRESHOLD_PX = 4;
var CORNER_SNAP_PX = 72;
var CLICK_SWALLOW_MS = 350;
function overlayPlacement(config) {
  const free = config.options.freePos;
  if (free === null || free === void 0) {
    return { className: "pos-" + config.options.position, style: void 0 };
  }
  const maxX = Math.max(8, (window.innerWidth || 1280) - 48);
  const maxY = Math.max(8, (window.innerHeight || 800) - 44);
  const x = Math.min(free.x, maxX);
  const y = Math.min(free.y, maxY);
  const style = {};
  if (free.anchor === "right") style.right = x + "px";
  else style.left = x + "px";
  if (free.vAnchor === "bottom") style.bottom = y + "px";
  else style.top = y + "px";
  return {
    className: "drc-free" + (free.anchor === "right" ? " drc-free-right" : "") + (free.vAnchor === "bottom" ? " drc-free-up" : ""),
    style
  };
}
function snapCorner(rect, vw, vh) {
  const right = vw - (rect.left + rect.width);
  const top = rect.top;
  const bottom = vh - (rect.top + rect.height);
  for (const position of POSITIONS) {
    const anchor = POSITION_ANCHORS[position.id];
    const dy = Math.abs(
      (anchor.top === void 0 ? bottom : top) - (anchor.top === void 0 ? anchor.bottom : anchor.top)
    );
    if (Math.abs(right - anchor.right) <= CORNER_SNAP_PX && dy <= CORNER_SNAP_PX) return position.id;
  }
  return null;
}
function freePosFrom(rect, vw, vh) {
  const centerX = rect.left + rect.width / 2;
  const centerY = rect.top + rect.height / 2;
  const anchor = centerX > vw / 2 ? "right" : "left";
  const vAnchor = centerY > vh / 2 ? "bottom" : "top";
  const maxX = Math.max(8, vw - rect.width - 8);
  const maxY = Math.max(8, vh - rect.height - 8);
  const edgeX = anchor === "right" ? vw - (rect.left + rect.width) : rect.left;
  const edgeY = vAnchor === "bottom" ? vh - (rect.top + rect.height) : rect.top;
  return {
    anchor,
    x: clampInt(edgeX, 8, maxX, 16),
    vAnchor,
    y: clampInt(edgeY, 8, maxY, 52)
  };
}
function OverlayEntry() {
  const snapshot = useStore(subscribe, getState, getState);
  const [open, setOpen] = useState(false);
  const openTimer = useRef(null);
  const closeTimer = useRef(null);
  const rootRef = useRef(null);
  const dragRef = useRef(null);
  const swallowClickAt = useRef(0);
  const [dragging, setDragging] = useState(false);
  const cancelTimers = () => {
    if (openTimer.current !== null) {
      window.clearTimeout(openTimer.current);
      openTimer.current = null;
    }
    if (closeTimer.current !== null) {
      window.clearTimeout(closeTimer.current);
      closeTimer.current = null;
    }
  };
  useEffect(
    () => () => {
      cancelTimers();
    },
    []
  );
  const openNow = () => {
    cancelTimers();
    setOpen(true);
  };
  const hoverOpen = () => {
    if (dragRef.current !== null) return;
    cancelTimers();
    openTimer.current = window.setTimeout(() => {
      openTimer.current = null;
      setOpen(true);
    }, HOVER_OPEN_MS);
  };
  const hoverClose = () => {
    if (dragRef.current !== null) return;
    cancelTimers();
    closeTimer.current = window.setTimeout(() => {
      closeTimer.current = null;
      setOpen(false);
    }, HOVER_CLOSE_MS);
  };
  const dragStart = (event) => {
    if (event.button !== void 0 && event.button !== 0) return;
    const node = event.currentTarget;
    const rect = node !== null && node !== void 0 && typeof node.getBoundingClientRect === "function" ? node.getBoundingClientRect() : { left: event.clientX, top: event.clientY, width: 0, height: 0 };
    dragRef.current = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, rect, moved: false };
    if (node !== null && node !== void 0 && typeof node.setPointerCapture === "function" && event.pointerId !== void 0) {
      node.setPointerCapture(event.pointerId);
    }
  };
  const dragMove = (event) => {
    const drag = dragRef.current;
    if (drag === null) return;
    if (drag.pointerId !== void 0 && event.pointerId !== void 0 && drag.pointerId !== event.pointerId) return;
    const dx = event.clientX - drag.startX;
    const dy = event.clientY - drag.startY;
    if (!drag.moved && Math.abs(dx) + Math.abs(dy) < DRAG_THRESHOLD_PX) return;
    drag.moved = true;
    if (!dragging) setDragging(true);
    cancelTimers();
    const node = rootRef.current;
    if (node !== null && node !== void 0 && node.style !== void 0)
      node.style.transform = "translate(" + dx + "px," + dy + "px)";
  };
  const dragEnd = (event) => {
    const drag = dragRef.current;
    if (drag === null) return;
    dragRef.current = null;
    const node = rootRef.current;
    if (node !== null && node !== void 0 && node.style !== void 0) node.style.transform = "";
    if (!drag.moved) return;
    setDragging(false);
    swallowClickAt.current = Date.now();
    const rect = {
      left: drag.rect.left + (event.clientX - drag.startX),
      top: drag.rect.top + (event.clientY - drag.startY),
      width: drag.rect.width || 0,
      height: drag.rect.height || 0
    };
    const vw = window.innerWidth || 1280;
    const vh = window.innerHeight || 800;
    const corner = snapCorner(rect, vw, vh);
    const next = cloneConfig(snapshot.config);
    next.options = Object.assign(
      {},
      next.options,
      corner === null ? { freePos: freePosFrom(rect, vw, vh) } : { freePos: null, position: corner }
    );
    saveConfig(next).catch((err) => {
      console.error("reminder-clock: saving the dragged position failed", err);
    });
  };
  const dragCancel = () => {
    const drag = dragRef.current;
    if (drag === null) return;
    dragRef.current = null;
    setDragging(false);
    const node = rootRef.current;
    if (node !== null && node !== void 0 && node.style !== void 0) node.style.transform = "";
  };
  const config = snapshot.config;
  if (!config.enabled && snapshot.alert === null) return null;
  if (snapshot.alert === null && !config.options.showCountdown) return null;
  const placement = overlayPlacement(config);
  const children = [];
  if (snapshot.alert !== null) {
    children.push(
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        AlertCard,
        {
          alert: snapshot.alert,
          snoozeMinutes: config.options.snoozeMinutes,
          onDismiss: () => setState({ alert: null }),
          onSnooze: () => {
            const alert = state.alert;
            if (alert === null) return;
            setState({
              alert: null,
              snoozes: state.snoozes.concat([
                {
                  item: alert.item,
                  atMs: Date.now() + config.options.snoozeMinutes * 6e4
                }
              ])
            });
          },
          onMute: muteToday
        },
        "alert"
      )
    );
  } else {
    children.push(
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        CountdownPill,
        {
          config,
          nowMs: snapshot.nowMs,
          open,
          onToggle: () => {
            const swallow = swallowClickAt.current !== 0 && Date.now() - swallowClickAt.current < CLICK_SWALLOW_MS;
            swallowClickAt.current = 0;
            if (swallow) return;
            if (open) setOpen(false);
            else openNow();
          },
          onHoverStart: hoverOpen,
          onHoverEnd: hoverClose,
          onDragStart: dragStart,
          onDragMove: dragMove,
          onDragEnd: dragEnd,
          onDragCancel: dragCancel
        },
        "pill"
      )
    );
    if (open) {
      children.push(
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
          SchedulePanel,
          {
            config,
            nowMs: snapshot.nowMs,
            muted: mutedDay() === dayKey(snapshot.nowMs),
            onMute: muteToday,
            onUnmute: unmuteToday,
            onHoverStart: openNow,
            onHoverEnd: hoverClose
          },
          "panel"
        )
      );
    }
  }
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
    "div",
    {
      className: "drc-root " + placement.className + (dragging ? " drc-dragging" : ""),
      style: placement.style,
      ref: rootRef,
      children
    }
  );
}
function ItemRow(props) {
  const { item, index, onChange, onRemove } = props;
  const [more, setMore] = useState(false);
  const patch = (fields) => onChange(index, Object.assign({}, item, fields));
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-item", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "button",
      {
        type: "button",
        className: "drc-more" + (more ? " drc-more-open" : "") + (item.message.length > 0 ? " drc-more-set" : ""),
        "aria-expanded": more,
        "aria-label": (more ? "收起" : "展开") + "「" + item.label + "」的提醒文案设置",
        onClick: () => setMore(!more),
        children: more ? "▾" : "▸"
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "input",
      {
        className: "drc-input drc-input-emoji",
        value: item.emoji,
        maxLength: 4,
        "aria-label": "图标",
        onChange: (event) => patch({ emoji: event.target.value })
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "input",
      {
        className: "drc-input",
        value: item.label,
        maxLength: 24,
        placeholder: "名称",
        "aria-label": "名称",
        onChange: (event) => patch({ label: event.target.value })
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "input",
      {
        className: "drc-input",
        type: "time",
        value: item.time,
        "aria-label": "时间",
        onChange: (event) => patch({ time: event.target.value })
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "select",
      {
        className: "drc-select",
        value: item.days,
        "aria-label": "适用日",
        onChange: (event) => patch({ days: event.target.value }),
        children: DAY_POLICIES.map((policy) => /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: policy.id, children: policy.label }, policy.id))
      }
    ),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { className: "drc-check", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "input",
        {
          type: "checkbox",
          checked: item.enabled,
          onChange: (event) => patch({ enabled: event.target.checked })
        }
      ),
      "启用"
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("button", { type: "button", className: "drc-btn", onClick: () => onRemove(index), "aria-label": "删除这一项", children: "删除" }),
    more ? /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-item-more", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-sub", children: "提醒文案" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "input",
        {
          className: "drc-input",
          value: item.message,
          maxLength: 120,
          placeholder: "到点时卡片上的正文，可留空（留空则用「到点了」）",
          "aria-label": "提醒文案",
          onChange: (event) => patch({ message: event.target.value })
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-sub", children: item.message.length + "/120" })
    ] }) : null
  ] });
}
function holidaysSummary(holidays, years) {
  const source = holidays.channel === "browser" ? "浏览器直连" : holidays.channel === "host" ? holidays.source === "network" ? "Host 联网同步" : holidays.source === "cache" ? "Host 磁盘缓存" : "Host 内置快照" : holidays.source === "local" ? "本地缓存" : "内置快照";
  const parts = ["节假日：" + source];
  if (years.length > 0) parts.push("覆盖 " + years.join("、"));
  if (typeof holidays.fetchedAt === "string" && holidays.fetchedAt.length > 0) {
    parts.push("同步于 " + holidays.fetchedAt.slice(0, 16).replace("T", " "));
  }
  return parts.join(" · ");
}
function CalendarPanel(props) {
  const { draft, update } = props;
  const calendar = draft.calendar;
  const [overrideDate, setOverrideDate] = useState("");
  const [overrideRest, setOverrideRest] = useState("1");
  const today = Date.now();
  const weekStart = mondayOf(today);
  const cycle = calendar.cycle;
  const holidays = state.holidays;
  const years = Object.keys(mergedHolidays).sort();
  const toggleWorkday = (which, day) => update((next) => {
    const list = next.calendar[which];
    const at = list.indexOf(day);
    if (at >= 0) list.splice(at, 1);
    else list.push(day);
    list.sort((a, b) => a - b);
  });
  const setCycle = (kind) => update((next) => {
    next.calendar.cycle = kind === "off" ? null : { anchor: dayKey(weekStart), anchorKind: kind };
  });
  const weekdayButtons = (which) => /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "drc-weekdays", children: WEEKDAY_LABELS.map((label, index) => {
    const day = index + 1;
    const on = calendar[which].indexOf(day) >= 0;
    return /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
      "button",
      {
        type: "button",
        className: "drc-weekday" + (on ? " drc-weekday-on" : ""),
        "aria-pressed": on,
        "aria-label": "周" + label,
        onClick: () => toggleWorkday(which, day),
        children: label
      },
      which + "-" + day
    );
  }) });
  const overrides = Object.entries(calendar.overrides).sort((a, b) => a[0] < b[0] ? -1 : 1);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-group", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-group-title", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: "工作日 · 大小周 · 节假日" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-daytag", children: dayChipLabel(today) + " " + dayInfoLabel(dayInfo(today, draft)) })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { className: "drc-check", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "input",
        {
          type: "checkbox",
          checked: cycle !== null,
          "aria-label": "启用大小周排班",
          onChange: () => setCycle(cycle === null ? "big" : "off")
        }
      ),
      "启用大小周排班"
    ] }),
    cycle === null ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-sub", children: "未启用：周一~周五上班，周六周日休息。" }) : /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-inline", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-sub", children: "本周（" + dayKey(weekStart).slice(5) + " 起）是" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
        "select",
        {
          className: "drc-select",
          value: cycle.anchorKind,
          "aria-label": "本周是大周还是小周",
          onChange: (event) => setCycle(event.target.value),
          children: [
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: "big", children: "大周" }),
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: "small", children: "小周" })
          ]
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-sub", children: "之后大小周交替" })
    ] }),
    cycle === null ? null : /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-inline", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-sub", children: "大周工作日" }),
      weekdayButtons("bigWorkdays")
    ] }),
    cycle === null ? null : /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-inline", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-sub", children: "小周工作日" }),
      weekdayButtons("smallWorkdays")
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { className: "drc-check", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "input",
        {
          type: "checkbox",
          checked: calendar.sync,
          "aria-label": "自动同步国家法定节假日",
          onChange: (event) => update((next) => {
            next.calendar.sync = event.target.checked;
          })
        }
      ),
      "自动同步国家法定节假日"
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-inline", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-sub", children: holidaysSummary(holidays, years) }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          className: "drc-btn",
          disabled: state.holidaySync === "syncing",
          onClick: () => {
            syncHolidays().catch(() => {
            });
          },
          children: state.holidaySync === "syncing" ? "同步中…" : "立即同步"
        }
      ),
      state.holidaySync === "done" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-status drc-status-ok", children: state.holidaySyncVia === "browser" ? "已同步（浏览器直连）" : "已同步（Host）" }) : null,
      state.holidaySync === "error" ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-status drc-status-err", children: "同步失败" }) : null
    ] }),
    state.holidaySync === "error" && state.holidaySyncError !== null ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-warn", children: "同步失败：" + state.holidaySyncError + "（继续用已有的快照 / 本地缓存，提醒不受影响）" }) : null,
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-sub", children: "同步优先走 Host（可多浏览器共用缓存），Host 半未重启时自动改用本页直连供应商；都拿不到就用内置快照。" }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-sub", children: "手动调整：单独指定某天放假或补班，优先于内置节假日表。" }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-inline", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "input",
        {
          className: "drc-input drc-date",
          type: "date",
          value: overrideDate,
          "aria-label": "日期",
          onChange: (event) => setOverrideDate(event.target.value)
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(
        "select",
        {
          className: "drc-select",
          value: overrideRest,
          "aria-label": "放假还是补班",
          onChange: (event) => setOverrideRest(event.target.value),
          children: [
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: "1", children: "放假" }),
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: "0", children: "补班" })
          ]
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          className: "drc-btn",
          disabled: !/^\d{4}-\d{2}-\d{2}$/.test(overrideDate),
          onClick: () => {
            update((next) => {
              next.calendar.overrides[overrideDate] = Number(overrideRest);
            });
            setOverrideDate("");
          },
          children: "添加"
        }
      )
    ] }),
    overrides.length === 0 ? null : /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "drc-override-list", children: overrides.map(([date, rest]) => /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "drc-override", children: [
      date + " " + (rest === 1 ? "放假" : "补班"),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          className: "drc-override-x",
          "aria-label": "删除 " + date,
          onClick: () => update((next) => {
            delete next.calendar.overrides[date];
          }),
          children: "×"
        }
      )
    ] }, date)) })
  ] });
}
function SettingsSection() {
  useStore(subscribe, settingsSnapshot, settingsSnapshot);
  const rev = state.configRev;
  const [draft, setDraft] = useState(() => cloneConfig(state.config));
  const [dirty, setDirty] = useState(false);
  const lastRev = useRef(rev);
  const saveState_ = state.saveState;
  const hostError = state.error;
  useEffect(() => {
    if (lastRev.current === rev) return;
    lastRev.current = rev;
    if (!dirty) setDraft(cloneConfig(state.config));
  }, [rev, dirty]);
  const update = (mutate) => {
    setDraft((current) => {
      const next = cloneConfig(current);
      mutate(next);
      return next;
    });
    setDirty(true);
  };
  const nextId = () => {
    let index = draft.items.length + 1;
    while (draft.items.some((item) => item.id === "item-" + index)) index += 1;
    return "item-" + index;
  };
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-settings", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-sec-head", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h2", { children: "作息提醒" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { children: "到点后在 DSH 窗口内弹出提醒卡片；平时右上角显示下一条提醒的倒计时，鼠标悬停即展开今日安排。每条可设适用日，工作日判定支持大小周与法定节假日。改完点「保存」写入 Host 磁盘，换浏览器、清缓存都不会丢。" })
    ] }),
    hostError !== null ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-warn", children: "未连上 Host 配置接口（" + hostError + "），修改只会保存在本浏览器。" }) : null,
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-group", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { className: "drc-check", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
          "input",
          {
            type: "checkbox",
            checked: draft.enabled,
            onChange: (event) => update((next) => {
              next.enabled = event.target.checked;
            })
          }
        ),
        "启用提醒"
      ] }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-hint", children: "关闭后不再弹卡片；下面的倒计时开关仍然有效。" })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-group", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-group-title", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: "提醒项（" + draft.items.length + "）" }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
          "button",
          {
            type: "button",
            className: "drc-btn",
            disabled: draft.items.length >= 24,
            onClick: () => update((next) => {
              next.items.push({
                id: nextId(),
                label: "新提醒",
                emoji: "⏰",
                time: "15:00",
                enabled: true,
                days: "every",
                message: ""
              });
            }),
            children: "+ 添加提醒项"
          }
        )
      ] }),
      draft.items.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-empty", children: "还没有提醒项，点右上角「+ 添加提醒项」。" }) : /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-item-head", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", {}),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: "图标" }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: "名称" }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: "时间" }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: "适用日" }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: "开关" }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: "操作" })
      ] }),
      draft.items.map((item, index) => /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        ItemRow,
        {
          item,
          index,
          onChange: (at, nextItem) => update((next) => {
            next.items[at] = nextItem;
          }),
          onRemove: (at) => update((next) => {
            next.items.splice(at, 1);
          })
        },
        item.id + "#" + index
      ))
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-group", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "drc-group-title", children: /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: "提醒行为" }) }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-options", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { className: "drc-check", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            "input",
            {
              type: "checkbox",
              checked: draft.options.showCountdown,
              onChange: (event) => update((next) => {
                next.options.showCountdown = event.target.checked;
              })
            }
          ),
          "显示常驻倒计时"
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { className: "drc-check", children: [
          "位置",
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            "select",
            {
              className: "drc-select",
              value: draft.options.position,
              onChange: (event) => update((next) => {
                next.options.position = event.target.value;
                next.options.freePos = null;
              }),
              children: POSITIONS.map((position) => /* @__PURE__ */ (0, import_jsx_runtime.jsx)("option", { value: position.id, children: position.label }, position.id))
            }
          )
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "drc-sub", children: draft.options.freePos === null ? "当前跟随上面的预设；也可以直接拖动胶囊到任意位置" : /* @__PURE__ */ (0, import_jsx_runtime.jsxs)(import_jsx_runtime.Fragment, { children: [
          "已自定义位置（拖动胶囊可继续微调）",
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            "button",
            {
              type: "button",
              className: "drc-btn",
              onClick: () => update((next) => {
                next.options.freePos = null;
              }),
              children: "回到预设位置"
            }
          )
        ] }) }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { className: "drc-check", children: [
          "稍后再提醒",
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            "input",
            {
              className: "drc-input drc-num",
              type: "number",
              min: 1,
              max: 120,
              value: draft.options.snoozeMinutes,
              onChange: (event) => update((next) => {
                next.options.snoozeMinutes = Number(event.target.value);
              })
            }
          ),
          "分钟"
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("label", { className: "drc-check", children: [
          "错过宽限",
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
            "input",
            {
              className: "drc-input drc-num",
              type: "number",
              min: 0,
              max: 60,
              value: draft.options.graceMinutes,
              onChange: (event) => update((next) => {
                next.options.graceMinutes = Number(event.target.value);
              })
            }
          ),
          "分钟"
        ] })
      ] }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "drc-hint", children: "宽限 = 页面没开着时错过的容错窗口：超过这个分钟数就不再补弹，避免打开 DSH 时被一串过期提醒糊脸。" })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(CalendarPanel, { draft, update }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "drc-actions", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          className: "drc-btn drc-btn-primary",
          disabled: saveState_ === "saving",
          onClick: () => {
            saveConfig(draft).then(() => {
              setDirty(false);
            }).catch(() => {
            });
          },
          children: saveState_ === "saving" ? "保存中…" : "保存"
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          className: "drc-btn",
          onClick: () => {
            setDraft(cloneConfig(state.config));
            setDirty(false);
          },
          disabled: !dirty,
          children: "放弃修改"
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "button",
        {
          type: "button",
          className: "drc-btn",
          onClick: () => {
            const defaults = defaultConfig();
            setDraft(defaults);
            setDirty(true);
          },
          children: "恢复默认"
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "span",
        {
          className: "drc-status" + (saveState_ === "saved" ? " drc-status-ok" : "") + (saveState_ === "error" ? " drc-status-err" : ""),
          children: saveState_ === "saved" ? "已保存" : saveState_ === "error" ? "保存失败：" + String(state.saveError) + "（本地已暂存）" : dirty ? "有未保存的修改" : "已是最新"
        }
      )
    ] })
  ] });
}
var name = "reminder-clock";
var inject = ["slots"];
function apply(ctx) {
  const style = document.createElement("style");
  style.setAttribute("data-dsh-reminder-clock", "");
  style.textContent = CSS;
  document.head.appendChild(style);
  ctx.effect(
    () => () => {
      style.remove();
    },
    "reminder-clock: css"
  );
  ctx.effect(() => {
    startEngine();
    return () => {
      stopEngine();
    };
  }, "reminder-clock: engine");
  const slots = ctx.slots;
  const OverlaySafe = () => /* @__PURE__ */ (0, import_jsx_runtime.jsx)(Boundary, { children: /* @__PURE__ */ (0, import_jsx_runtime.jsx)(OverlayEntry, {}) });
  const SettingsSafe = () => /* @__PURE__ */ (0, import_jsx_runtime.jsx)(Boundary, { children: /* @__PURE__ */ (0, import_jsx_runtime.jsx)(SettingsSection, {}) });
  slots.inject(
    "shell.overlay",
    () => slots.register(
      {
        name: "shell.overlay",
        id: "reminder-clock",
        order: 30,
        label: () => "作息提醒"
      },
      OverlaySafe
    )
  );
  slots.inject(
    "settings.section",
    () => slots.register(
      {
        name: "settings.section",
        id: "reminder-clock",
        order: 140,
        label: () => "作息提醒"
      },
      SettingsSafe
    )
  );
  loadConfig().catch((err) => {
    setState({ status: "ready", error: messageOf(err) });
  });
  loadHolidays().catch((err) => {
    console.error("reminder-clock: holiday load failed", err);
  });
}

    return module.exports;
  },
});
