// Build the two runtime artifacts from src/.
//
//   node scripts/build.mjs            one-shot build
//   node scripts/build.mjs --watch    rebuild on save (client HMR picks it up)
//
//   src/index.mjs         -> lib/index.mjs   (Node ESM; ./holidays.mjs inlined)
//   src/client/index.tsx  -> lib/client.js   (browser CJS bundle wrapped in the
//                                             ModuleLoader handoff contract)
//
// Both halves import the same generated holiday snapshot (src/holidays.mjs,
// written by scripts/fetch-holidays.mjs), so it is bundled into each artifact:
// no runtime sibling-module lookup, and the client stays usable offline.
//
// The client bundle keeps `react` / `react/jsx-runtime` external on purpose:
// those are platform seed modules the DSH loader hands to the factory. Anything
// else must be bundled in (the loader's `require` throws on an unknown specifier).
import { build, context } from 'esbuild'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const lib = join(root, 'lib')

/** Stable client entry id — must match the package name DSH advertises. */
const CLIENT_ID = 'dsh-reminder-clock'

/** Modules the browser loader owns (platform seed words). */
const CLIENT_EXTERNALS = ['react', 'react/jsx-runtime', 'react-dom', 'react-dom/client']

const clientOptions = {
  entryPoints: [join(root, 'src/client/index.tsx')],
  bundle: true,
  format: 'cjs',
  platform: 'browser',
  target: ['es2020'],
  jsx: 'automatic',
  charset: 'utf8',
  external: CLIENT_EXTERNALS,
  write: false,
  legalComments: 'none',
  logLevel: 'silent',
}

const hostOptions = {
  entryPoints: [join(root, 'src/index.mjs')],
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: ['node22'],
  packages: 'external',
  charset: 'utf8',
  write: false,
  legalComments: 'none',
  logLevel: 'silent',
}

/** `kind` is ours, never esbuild's. */
const TARGETS = [
  { kind: 'client', options: clientOptions },
  { kind: 'host', options: hostOptions },
]

function fail(message) {
  console.error('build failed: ' + message)
  process.exit(1)
}

/** Wrap the CJS bundle in the contract the browser loader expects. */
function wrapClient(code) {
  return [
    '// Generated by scripts/build.mjs — do not edit; edit src/client/index.tsx.',
    'window.__ModuleLoader__.load({',
    `  id: ${JSON.stringify(CLIENT_ID)},`,
    '  factory: (require) => {',
    '    var module = { exports: {} };',
    '    var exports = module.exports;',
    code,
    '    return module.exports;',
    '  },',
    '});',
    '',
  ].join('\n')
}

/** Years present in the generated holiday snapshot. */
async function holidayYears() {
  const data = await import(pathToFileURL(join(root, 'src/holidays.mjs')).href)
  return Object.keys(data.BUNDLED_HOLIDAYS)
}

async function emitClient(result) {
  const code = result.outputFiles[0].text
  const wrapped = wrapClient(code)
  if (!wrapped.includes('__ModuleLoader__.load(')) fail('client bundle lost the loader handoff')
  if (!wrapped.includes('require("react/jsx-runtime")')) fail('client bundle is not using the JSX automatic runtime')
  for (const year of await holidayYears()) {
    if (!new RegExp('["\']?' + year + '["\']?\\s*:').test(wrapped))
      fail('client bundle is missing holiday year ' + year)
  }
  writeFileSync(join(lib, 'client.js'), wrapped, 'utf8')
}

async function emitHost(result) {
  const code = result.outputFiles[0].text
  const target = join(lib, 'index.mjs')
  writeFileSync(target, code, 'utf8')
  // Strong check: actually load it and look at the plugin surface.
  const module = await import(pathToFileURL(target).href + '?built=' + Date.now())
  if (module.name !== 'reminder-clock') fail('lib/index.mjs does not export name = reminder-clock')
  if (!Array.isArray(module.inject) || !module.inject.includes('webServer'))
    fail('lib/index.mjs does not inject webServer')
  if (typeof module.apply !== 'function') fail('lib/index.mjs does not export apply()')
}

const emitPlugin = (kind) => ({
  name: 'drc-emit-' + kind,
  setup(buildApi) {
    buildApi.onEnd(async (result) => {
      if (result.errors.length > 0) return
      if (kind === 'client') await emitClient(result)
      else await emitHost(result)
      console.log('built lib/' + (kind === 'client' ? 'client.js' : 'index.mjs'))
    })
  },
})

mkdirSync(lib, { recursive: true })
// lib/holidays.mjs is no longer an artifact: both halves bundle the snapshot.
rmSync(join(lib, 'holidays.mjs'), { force: true })

const withEmit = (target) => Object.assign({}, target.options, { plugins: [emitPlugin(target.kind)] })

if (process.argv.includes('--watch')) {
  for (const target of TARGETS) {
    const ctx = await context(withEmit(target))
    await ctx.watch()
  }
  console.log(
    'watching src/ — save to rebuild; the client half reaches the open page in ~3s, the host half needs a DSH restart',
  )
} else {
  for (const target of TARGETS) {
    await build(withEmit(target))
  }
  const years = await holidayYears()
  console.log(`build ok — holidays ${years.join(', ')} bundled into both halves`)
}
